#0 // JP s
SETPC

#1 // RETD e
TRANSFER MSP PCSL INC(SP)
TRANSFER MSP PCSH INC(SP)
TRANSFER MSP PCP  INC(SP)
JMP #9 // LBPX MX, e

#2 // JP C, s
JMP NC #95 // If carry not set, NOP
SETPC BOTH

#3 // JP NC, s
JMP C #95 // If carry set, NOP
SETPC BOTH

#4 // CALL s
// TODO

#5 // CALZ s
// TODO

#6 // JP Z, s
JMP NZ #95 // If zero not set, NOP
SETPC BOTH

#7 // JP NZ, s
JMP Z #95 // If zero set, NOP
SETPC BOTH

#8 // LD Y, e
TRANSFER IMMH YH
TRANSFER IMML YL

#9 // LBPX MX, e
TRANSFER IMML MX INC(XHL)
TRANSFER IMMH MX INC(XHL)

#10 // ADC XH, i
TRANSFER XH TEMPA
TRANSFER IMML TEMPB
TRANSALU ADC_NO_DEC XH

#11 // ADC XL, i
TRANSFER XL TEMPA
TRANSFER IMML TEMPB
TRANSALU ADC_NO_DEC XL

#12 // ADC YH, i
TRANSFER YH TEMPA
TRANSFER IMML TEMPB
TRANSALU ADC_NO_DEC YH

#13 // ADC YL, i
TRANSFER YL TEMPA
TRANSFER IMML TEMPB
TRANSALU ADC_NO_DEC YL

#14 // CP XH, i
TRANSFER XH TEMPA
TRANSFER IMML TEMPB
TRANSALU CP TEMPA

#15 // CP XL, i
TRANSFER XL TEMPA
TRANSFER IMML TEMPB
TRANSALU CP TEMPA

#16 // CP YH, i
TRANSFER YH TEMPA
TRANSFER IMML TEMPB
TRANSALU CP TEMPA

#17 // CP YL, i
TRANSFER YL TEMPA
TRANSFER IMML TEMPB
TRANSALU CP TEMPA

#18 // ADD r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU ADD IMM_ADDR_H

#19 // ADC r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU ADC IMM_ADDR_H

#20 // SUB r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU SUB IMM_ADDR_H

#21 // SBC r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU SBC IMM_ADDR_H

#22 // AND r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU AND IMM_ADDR_H

#23 // OR r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU OR IMM_ADDR_H

#24 // XOR r, q
TRANSFER IMM_ADDR_H TEMPA
TRANSFER IMM_ADDR_L TEMPB
TRANSALU XOR IMM_ADDR_H

#25 // RLC r
TRANSFER IMM_ADDR_L TEMPA
TRANSALU RLC IMM_ADDR_L

#26 // LD X, e
TRANSFER IMMH XH
TRANSFER IMML XL

#27 // ADD r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU ADD IMM_ADDR_P

#28 // ADC r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU ADC IMM_ADDR_P

#29 // AND r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU AND IMM_ADDR_P

#30 // OR r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU OR IMM_ADDR_P

#31 // XOR r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU XOR IMM_ADDR_P

#32 // SBC r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU SBC IMM_ADDR_P

#33 // FAN r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU SBC TEMPA // Transfer result _somewhere_, and transfer zero flag

#34 // CP r, i
TRANSFER IMM_ADDR_P TEMPA
TRANSFER IMML TEMPB
TRANSALU CP TEMPA

#35 // LD r, i
TRANSFER IMML IMM_ADDR_P
